# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-20 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WechatSpider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(default='general_html_spider', max_length=20, verbose_name='\u4f7f\u7528\u7684\u722c\u866b\u63a5\u53e3')),
                ('days_range', models.IntegerField(verbose_name='\u65f6\u95f4\u8303\u56f4')),
                ('key_words', models.CharField(default='\u597d\u672a\u6765', max_length=16, verbose_name='\u5173\u952e\u5b57')),
                ('current_status', models.CharField(default='\u5c31\u7eea', max_length=4, verbose_name='\u5f53\u524d\u72b6\u6001')),
                ('description', models.TextField(blank=True, null=True, verbose_name='\u63cf\u8ff0')),
                ('db_host', models.CharField(default='103.235.226.201', max_length=16, verbose_name='Host')),
                ('db_name', models.CharField(default='spider_system', max_length=32, verbose_name='\u6570\u636e\u5e93\u540d')),
                ('db_user', models.CharField(default='stat2016', max_length=32, verbose_name='\u7528\u6237\u540d')),
                ('db_password', models.CharField(default='stat2016', max_length=32, verbose_name='\u5bc6\u7801')),
            ],
            options={
                'verbose_name': '\u5fae\u4fe1\u722c\u866b',
                'verbose_name_plural': '\u5fae\u4fe1\u722c\u866b',
            },
        ),
    ]
