# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-20 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_show', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.CharField(default='0', max_length=32, verbose_name='\u6587\u7ae0id')),
                ('title', models.CharField(default='', max_length=150, verbose_name='\u6587\u7ae0\u6807\u9898')),
                ('date', models.CharField(max_length=20, verbose_name='\u65f6\u95f4')),
                ('origin', models.CharField(default='', max_length=25, verbose_name='\u6765\u6e90')),
                ('content', models.TextField(verbose_name='\u9875\u9762\u8be6\u60c5')),
                ('status', models.IntegerField(max_length=11, verbose_name='\u72b6\u6001')),
            ],
            options={
                'verbose_name': '\u6587\u7ae0\u8be6\u60c5',
                'verbose_name_plural': '\u6587\u7ae0\u8be6\u60c5',
            },
        ),
    ]
