# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-20 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_show', '0002_articledetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articledetail',
            name='status',
            field=models.IntegerField(verbose_name='\u72b6\u6001'),
        ),
    ]
