# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-25 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_show', '0003_auto_20171220_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=150)),
                ('brief', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=20)),
                ('origin', models.CharField(max_length=50)),
                ('origin_name', models.CharField(max_length=40)),
                ('platform', models.IntegerField(max_length=11)),
                ('article_id', models.CharField(max_length=32)),
                ('category_id', models.IntegerField(max_length=11)),
                ('update_date', models.CharField(max_length=20)),
                ('status', models.IntegerField(max_length=11)),
                ('article_type', models.CharField(max_length=10)),
                ('cover_photo_id', models.CharField(max_length=32)),
                ('cover_photo_url', models.CharField(max_length=100)),
                ('cover_photo_show_type', models.IntegerField(max_length=11)),
                ('views_no', models.IntegerField(default=0, max_length=11)),
                ('replies_no', models.IntegerField(default=0, max_length=11)),
            ],
            options={
                'verbose_name': '\u6587\u7ae0\u7ba1\u7406',
                'verbose_name_plural': '\u6587\u7ae0\u7ba1\u7406',
            },
        ),
        migrations.DeleteModel(
            name='WechatSpider',
        ),
    ]
