# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-25 02:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_show', '0004_auto_20171225_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=150)),
                ('image_id', models.CharField(max_length=32)),
                ('status', models.IntegerField(max_length=4)),
            ],
            options={
                'verbose_name': '\u56fe\u7247\u7ba1\u7406',
                'verbose_name_plural': '\u56fe\u7247\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='WeiXin',
            fields=[
                ('create_date', models.DateTimeField()),
                ('wei_xin', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('wei_xin_name', models.CharField(max_length=20)),
                ('classify_id', models.IntegerField(max_length=11)),
                ('tags', models.CharField(max_length=100)),
                ('is_delete', models.IntegerField(max_length=11)),
                ('update_date', models.DateTimeField()),
            ],
            options={
                'verbose_name': '\u5fae\u4fe1\u516c\u4f17\u53f7',
                'verbose_name_plural': '\u5fae\u4fe1\u516c\u4f17\u53f7',
            },
        ),
    ]
