# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-25 03:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('data_show', '0005_images_weixin'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemMeta',
            fields=[
                ('item_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('category', models.IntegerField(default=None, max_length=11)),
                ('properties', models.CharField(default=None, max_length=200)),
                ('updatetime', models.DateTimeField(default=datetime.datetime(2017, 12, 25, 3, 7, 58, 39000, tzinfo=utc))),
            ],
            options={
                'db_table': 'item_meta',
                'verbose_name': '\u9879\u76ee\u7ba1\u7406',
                'verbose_name_plural': '\u9879\u76ee\u7ba1\u7406',
            },
        ),
    ]
