# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-25 03:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('data_show', '0006_itemmeta'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='Articles',
        ),
        migrations.AlterField(
            model_name='itemmeta',
            name='updatetime',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 25, 3, 9, 23, 191000, tzinfo=utc)),
        ),
        migrations.AlterModelTable(
            name='articles',
            table='articles',
        ),
    ]
