# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-25 03:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('data_show', '0007_auto_20171225_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classify',
            fields=[
                ('category_id', models.IntegerField(max_length=11, primary_key=True, serialize=False)),
                ('category_name', models.CharField(default=None, max_length=20)),
                ('order', models.IntegerField(max_length=11)),
                ('is_delete', models.IntegerField(max_length=1)),
            ],
            options={
                'db_table': 'classify',
                'verbose_name': '\u5206\u7c7b',
                'verbose_name_plural': '\u5206\u7c7b',
            },
        ),
        migrations.CreateModel(
            name='IgnoreUrl',
            fields=[
                ('url_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('add_date', models.DateTimeField(default=datetime.datetime(2017, 12, 25, 3, 20, 16, 76000, tzinfo=utc))),
            ],
            options={
                'db_table': 'ignore_url',
                'verbose_name': '\u8fc7\u6ee4\u7684url',
                'verbose_name_plural': '\u8fc7\u6ee4\u7684url',
            },
        ),
        migrations.AlterField(
            model_name='itemmeta',
            name='updatetime',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 25, 3, 20, 16, 76000, tzinfo=utc)),
        ),
        migrations.AlterModelTable(
            name='articledetail',
            table='article_detail',
        ),
        migrations.AlterModelTable(
            name='images',
            table='images',
        ),
        migrations.AlterModelTable(
            name='weixin',
            table='wei_xin',
        ),
    ]
