# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-25 06:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('data_show', '0008_auto_20171225_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_check_url', models.CharField(max_length=100)),
                ('access_token', models.CharField(max_length=100)),
                ('timestamp', models.IntegerField()),
            ],
            options={
                'db_table': 'api_token',
                'verbose_name': 'APIToken',
                'verbose_name_plural': 'APIToken',
            },
        ),
        migrations.AlterField(
            model_name='articles',
            name='category_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='articles',
            name='cover_photo_show_type',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='articles',
            name='platform',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='articles',
            name='replies_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='articles',
            name='status',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='classify',
            name='category_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='classify',
            name='is_delete',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='classify',
            name='order',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ignoreurl',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 25, 6, 52, 15, 38000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='images',
            name='status',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='itemmeta',
            name='category',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='itemmeta',
            name='updatetime',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 25, 6, 52, 15, 38000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='weixin',
            name='classify_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='weixin',
            name='is_delete',
            field=models.IntegerField(),
        ),
    ]
