# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-25 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_show', '0010_auto_20171225_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ignoreurl',
            name='add_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='itemmeta',
            name='updatetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='weixin',
            name='create_date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='weixin',
            name='is_delete',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='weixin',
            name='tags',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='weixin',
            name='update_date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='weixin',
            name='wei_xin_name',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
