# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-25 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_show', '0011_auto_20171225_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weixin',
            name='tags',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
