# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-25 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_show', '0012_auto_20171225_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='replies_no',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='articles',
            name='views_no',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='itemmeta',
            name='category',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='weixin',
            name='is_delete',
            field=models.IntegerField(default=0),
        ),
    ]
