# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-25 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_show', '0013_auto_20171225_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='cover_photo_show_type',
            field=models.IntegerField(default=None),
        ),
    ]
