# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-31 07:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_show', '0017_auto_20171231_1513'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moviewords',
            old_name='count',
            new_name='counts',
        ),
    ]
