# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-25 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaiduindexSpider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(default='Baidu_index', max_length=20)),
                ('key_word', models.CharField(max_length=16, verbose_name='\u5173\u952e\u5b57')),
                ('current_status', models.CharField(default='\u5c31\u7eea', max_length=4, verbose_name='\u5f53\u524d\u72b6\u6001')),
                ('description', models.TextField(blank=True, null=True, verbose_name='\u63cf\u8ff0')),
                ('db_host', models.CharField(default='103.235.226.211', max_length=16, verbose_name='Host')),
                ('db_name', models.CharField(default='mark_research', max_length=32, verbose_name='\u6570\u636e\u5e93\u540d')),
                ('db_user', models.CharField(default='mark_research_admin', max_length=32, verbose_name='\u7528\u6237\u540d')),
                ('db_password', models.CharField(default='3sD4#dfGsDVy6Gj6', max_length=32, verbose_name='\u5bc6\u7801')),
            ],
            options={
                'verbose_name': '\u767e\u5ea6\u6307\u6570\u722c\u866b',
                'verbose_name_plural': '\u767e\u5ea6\u6307\u6570\u722c\u866b',
            },
        ),
        migrations.CreateModel(
            name='GeneralNewsSpider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(default='general_html_spider', max_length=20, verbose_name='\u4f7f\u7528\u7684\u722c\u866b\u63a5\u53e3')),
                ('web', models.CharField(choices=[('\u7f51\u6613\u65b0\u95fb', '\u7f51\u6613\u65b0\u95fb'), ('\u817e\u8baf\u65b0\u95fb', '\u817e\u8baf\u65b0\u95fb')], max_length=5, verbose_name='\u8981\u722c\u53d6\u7684\u65b0\u95fb\u7f51\u7ad9')),
                ('scope_type', models.CharField(choices=[('\u65b0\u95fb\u5168\u6587', '\u65b0\u95fb\u5168\u6587'), ('\u65b0\u95fb\u6807\u9898', '\u65b0\u95fb\u6807\u9898')], max_length=4, verbose_name='\u68c0\u7d22\u8303\u56f4')),
                ('order', models.CharField(choices=[('\u6309\u65f6\u95f4\u6392\u5e8f', '\u6309\u65f6\u95f4\u6392\u5e8f'), ('\u6309\u7126\u70b9\u6392\u5e8f', '\u6309\u7126\u70b9\u6392\u5e8f')], max_length=6, verbose_name='\u6392\u5e8f\u65b9\u5f0f')),
                ('current_status', models.CharField(default='\u5c31\u7eea', max_length=4, verbose_name='\u5f53\u524d\u72b6\u6001')),
                ('description', models.TextField(blank=True, null=True, verbose_name='\u63cf\u8ff0')),
                ('db_host', models.CharField(default='103.235.226.211', max_length=16, verbose_name='Host')),
                ('db_name', models.CharField(default='mark_research', max_length=32, verbose_name='\u6570\u636e\u5e93\u540d')),
                ('db_user', models.CharField(default='mark_research_admin', max_length=32, verbose_name='\u7528\u6237\u540d')),
                ('db_password', models.CharField(default='3sD4#dfGsDVy6Gj6', max_length=32, verbose_name='\u5bc6\u7801')),
            ],
            options={
                'verbose_name': '\u65b0\u95fb\u722c\u866b',
                'verbose_name_plural': '\u65b0\u95fb\u722c\u866b',
            },
        ),
        migrations.CreateModel(
            name='JiazhangbangSpider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(default='general_json_spider', max_length=20, verbose_name='\u4f7f\u7528\u7684\u722c\u866b\u63a5\u53e3')),
                ('range_type', models.CharField(choices=[('\u6309\u5929\u722c\u53d6', '\u6309\u5929\u722c\u53d6'), ('\u6309\u9875\u722c\u53d6', '\u6309\u9875\u722c\u53d6')], max_length=5, verbose_name='\u722c\u53d6\u65b9\u5f0f')),
                ('range', models.IntegerField(verbose_name='\u722c\u53d6\u9875/\u5929\u6570')),
                ('current_status', models.CharField(default='\u5c31\u7eea', max_length=4, verbose_name='\u5f53\u524d\u72b6\u6001')),
                ('description', models.TextField(blank=True, null=True, verbose_name='\u63cf\u8ff0')),
                ('db_host', models.CharField(default='103.235.226.211', max_length=16, verbose_name='Host')),
                ('db_name', models.CharField(default='mark_research', max_length=32, verbose_name='\u6570\u636e\u5e93\u540d')),
                ('db_user', models.CharField(default='mark_research_admin', max_length=32, verbose_name='\u7528\u6237\u540d')),
                ('db_password', models.CharField(default='3sD4#dfGsDVy6Gj6', max_length=32, verbose_name='\u5bc6\u7801')),
            ],
            options={
                'verbose_name': '\u5bb6\u957f\u5e2e',
                'verbose_name_plural': '\u5bb6\u957f\u5e2e',
            },
        ),
        migrations.CreateModel(
            name='JiemoduiSpider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(default='general_json_spider', max_length=20, verbose_name='\u4f7f\u7528\u7684\u722c\u866b\u63a5\u53e3')),
                ('range_type', models.CharField(choices=[('\u6309\u5929\u722c\u53d6', '\u6309\u5929\u722c\u53d6'), ('\u6309\u9875\u722c\u53d6', '\u6309\u9875\u722c\u53d6')], max_length=5, verbose_name='\u722c\u53d6\u65b9\u5f0f')),
                ('range', models.IntegerField(verbose_name='\u722c\u53d6\u9875/\u5929\u6570')),
                ('current_status', models.CharField(default='\u5c31\u7eea', max_length=4, verbose_name='\u5f53\u524d\u72b6\u6001')),
                ('description', models.TextField(blank=True, null=True, verbose_name='\u63cf\u8ff0')),
                ('db_host', models.CharField(default='103.235.226.211', max_length=16, verbose_name='Host')),
                ('db_name', models.CharField(default='mark_research', max_length=32, verbose_name='\u6570\u636e\u5e93\u540d')),
                ('db_user', models.CharField(default='mark_research_admin', max_length=32, verbose_name='\u7528\u6237\u540d')),
                ('db_password', models.CharField(default='3sD4#dfGsDVy6Gj6', max_length=32, verbose_name='\u5bc6\u7801')),
            ],
            options={
                'verbose_name': '\u82a5\u672b\u5806',
                'verbose_name_plural': '\u82a5\u672b\u5806',
            },
        ),
        migrations.CreateModel(
            name='KaoyanbangSpider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(default='general_html_spider', max_length=20, verbose_name='\u4f7f\u7528\u7684\u722c\u866b\u63a5\u53e3')),
                ('days_range', models.IntegerField(verbose_name='\u65f6\u95f4\u8303\u56f4')),
                ('search_type', models.CharField(choices=[('\u6807\u9898\u641c\u7d22', '\u6807\u9898\u641c\u7d22'), ('\u5168\u6587\u641c\u7d22', '\u5168\u6587\u641c\u7d22')], max_length=10, verbose_name='\u641c\u7d22\u7c7b\u578b')),
                ('search_time_range', models.CharField(choices=[('\u4e00\u5c0f\u65f6\u4e4b\u5185', '\u4e00\u5c0f\u65f6\u4e4b\u5185'), ('\u4e00\u5468\u4e4b\u5185', '\u4e00\u5468\u4e4b\u5185'), ('\u4e00\u4e2a\u6708\u4e4b\u5185', '\u4e00\u4e2a\u6708\u4e4b\u5185'), ('\u4e00\u5929\u4e4b\u5185', '\u4e00\u5929\u4e4b\u5185')], max_length=10, verbose_name='\u65f6\u95f4\u8303\u56f4')),
                ('search_order', models.CharField(choices=[('\u6309\u65f6\u95f4\u6392\u5e8f', '\u6309\u65f6\u95f4\u6392\u5e8f'), ('\u9ed8\u8ba4\u6392\u5e8f', '\u9ed8\u8ba4\u6392\u5e8f')], max_length=10, verbose_name='\u6392\u5e8f\u65b9\u5f0f')),
                ('current_status', models.CharField(default='\u5c31\u7eea', max_length=4, verbose_name='\u5f53\u524d\u72b6\u6001')),
                ('description', models.TextField(blank=True, null=True, verbose_name='\u63cf\u8ff0')),
                ('db_host', models.CharField(default='103.235.226.211', max_length=16, verbose_name='Host')),
                ('db_name', models.CharField(default='mark_research', max_length=32, verbose_name='\u6570\u636e\u5e93\u540d')),
                ('db_user', models.CharField(default='mark_research_admin', max_length=32, verbose_name='\u7528\u6237\u540d')),
                ('db_password', models.CharField(default='3sD4#dfGsDVy6Gj6', max_length=32, verbose_name='\u5bc6\u7801')),
            ],
            options={
                'verbose_name': '\u8003\u7814\u5e2e\u722c\u866b',
                'verbose_name_plural': '\u8003\u7814\u5e2e\u722c\u866b',
            },
        ),
        migrations.CreateModel(
            name='TiebaSpider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(default='general_html_spider', max_length=20, verbose_name='\u4f7f\u7528\u7684\u722c\u866b\u63a5\u53e3')),
                ('order', models.CharField(choices=[('\u6309\u65f6\u95f4\u987a\u5e8f', '\u6309\u65f6\u95f4\u987a\u5e8f'), ('\u6309\u65f6\u95f4\u5012\u5e8f', '\u6309\u65f6\u95f4\u5012\u5e8f'), ('\u6309\u76f8\u5173\u6027\u5012\u5e8f', '\u6309\u76f8\u5173\u6027\u5012\u5e8f'), ('\u53ea\u770b\u4e3b\u9898\u8d34', '\u53ea\u770b\u4e3b\u9898\u8d34')], max_length=6, verbose_name='\u6392\u5e8f\u65b9\u5f0f')),
                ('days_range', models.IntegerField(verbose_name='\u65f6\u95f4\u8303\u56f4')),
                ('current_status', models.CharField(default='\u5c31\u7eea', max_length=4, verbose_name='\u5f53\u524d\u72b6\u6001')),
                ('description', models.TextField(blank=True, null=True, verbose_name='\u63cf\u8ff0')),
                ('db_host', models.CharField(default='103.235.226.211', max_length=16, verbose_name='Host')),
                ('db_name', models.CharField(default='mark_research', max_length=32, verbose_name='\u6570\u636e\u5e93\u540d')),
                ('db_user', models.CharField(default='mark_research_admin', max_length=32, verbose_name='\u7528\u6237\u540d')),
                ('db_password', models.CharField(default='3sD4#dfGsDVy6Gj6', max_length=32, verbose_name='\u5bc6\u7801')),
            ],
            options={
                'verbose_name': '\u8d34\u5427\u722c\u866b',
                'verbose_name_plural': '\u8d34\u5427\u722c\u866b',
            },
        ),
        migrations.CreateModel(
            name='ToutiaoSpider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(default='general_json_spider', max_length=20, verbose_name='\u4f7f\u7528\u7684\u722c\u866b\u63a5\u53e3')),
                ('range_type', models.CharField(choices=[('\u6309\u5929\u722c\u53d6', '\u6309\u5929\u722c\u53d6'), ('\u6309\u9875\u722c\u53d6', '\u6309\u9875\u722c\u53d6')], max_length=5, verbose_name='\u722c\u53d6\u65b9\u5f0f')),
                ('range', models.IntegerField(verbose_name='\u722c\u53d6\u9875/\u5929\u6570')),
                ('current_status', models.CharField(default='\u5c31\u7eea', max_length=4, verbose_name='\u5f53\u524d\u72b6\u6001')),
                ('description', models.TextField(blank=True, null=True, verbose_name='\u63cf\u8ff0')),
                ('db_host', models.CharField(default='103.235.226.211', max_length=16, verbose_name='Host')),
                ('db_name', models.CharField(default='mark_research', max_length=32, verbose_name='\u6570\u636e\u5e93\u540d')),
                ('db_user', models.CharField(default='mark_research_admin', max_length=32, verbose_name='\u7528\u6237\u540d')),
                ('db_password', models.CharField(default='3sD4#dfGsDVy6Gj6', max_length=32, verbose_name='\u5bc6\u7801')),
            ],
            options={
                'verbose_name': '\u4eca\u65e5\u5934\u6761',
                'verbose_name_plural': '\u4eca\u65e5\u5934\u6761',
            },
        ),
        migrations.CreateModel(
            name='WechatSpider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(default='general_html_spider', max_length=20, verbose_name='\u4f7f\u7528\u7684\u722c\u866b\u63a5\u53e3')),
                ('days_range', models.IntegerField(verbose_name='\u65f6\u95f4\u8303\u56f4')),
                ('current_status', models.CharField(default='\u5c31\u7eea', max_length=4, verbose_name='\u5f53\u524d\u72b6\u6001')),
                ('description', models.TextField(blank=True, null=True, verbose_name='\u63cf\u8ff0')),
                ('db_host', models.CharField(default='103.235.226.211', max_length=16, verbose_name='Host')),
                ('db_name', models.CharField(default='mark_research', max_length=32, verbose_name='\u6570\u636e\u5e93\u540d')),
                ('db_user', models.CharField(default='mark_research_admin', max_length=32, verbose_name='\u7528\u6237\u540d')),
                ('db_password', models.CharField(default='3sD4#dfGsDVy6Gj6', max_length=32, verbose_name='\u5bc6\u7801')),
            ],
            options={
                'verbose_name': '\u5fae\u4fe1\u722c\u866b',
                'verbose_name_plural': '\u5fae\u4fe1\u722c\u866b',
            },
        ),
    ]
