# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-25 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider_board', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jiazhangbangspider',
            name='range',
        ),
        migrations.RemoveField(
            model_name='jiazhangbangspider',
            name='range_type',
        ),
        migrations.RemoveField(
            model_name='jiemoduispider',
            name='range',
        ),
        migrations.RemoveField(
            model_name='jiemoduispider',
            name='range_type',
        ),
        migrations.RemoveField(
            model_name='toutiaospider',
            name='range',
        ),
        migrations.RemoveField(
            model_name='toutiaospider',
            name='range_type',
        ),
        migrations.AddField(
            model_name='jiazhangbangspider',
            name='days_range',
            field=models.IntegerField(default=20, verbose_name='\u722c\u53d6\u5929\u6570'),
        ),
        migrations.AddField(
            model_name='jiazhangbangspider',
            name='pages_range',
            field=models.IntegerField(default=5, verbose_name='\u722c\u53d6\u9875\u6570'),
        ),
        migrations.AddField(
            model_name='jiemoduispider',
            name='days_range',
            field=models.IntegerField(default=20, verbose_name='\u722c\u53d6\u5929\u6570'),
        ),
        migrations.AddField(
            model_name='jiemoduispider',
            name='pages_range',
            field=models.IntegerField(default=5, verbose_name='\u722c\u53d6\u9875\u6570'),
        ),
        migrations.AddField(
            model_name='toutiaospider',
            name='days_range',
            field=models.IntegerField(default=20, verbose_name='\u722c\u53d6\u5929\u6570'),
        ),
        migrations.AddField(
            model_name='toutiaospider',
            name='pages_range',
            field=models.IntegerField(default=5, verbose_name='\u722c\u53d6\u9875\u6570'),
        ),
    ]
