# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-25 10:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spider_board', '0002_auto_20170725_1553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jiazhangbangspider',
            old_name='pages_range',
            new_name='batch_size',
        ),
        migrations.RenameField(
            model_name='jiemoduispider',
            old_name='pages_range',
            new_name='batch_size',
        ),
        migrations.RenameField(
            model_name='toutiaospider',
            old_name='pages_range',
            new_name='batch_size',
        ),
    ]
