# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-26 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider_board', '0003_auto_20170725_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baiduindexspider',
            name='key_word',
        ),
        migrations.AddField(
            model_name='baiduindexspider',
            name='key_words',
            field=models.CharField(default='\u597d\u672a\u6765', max_length=16, verbose_name='\u5173\u952e\u5b57'),
        ),
        migrations.AddField(
            model_name='generalnewsspider',
            name='key_words',
            field=models.CharField(default='\u597d\u672a\u6765', max_length=16, verbose_name='\u5173\u952e\u5b57'),
        ),
        migrations.AddField(
            model_name='jiazhangbangspider',
            name='key_words',
            field=models.CharField(default='\u597d\u672a\u6765', max_length=16, verbose_name='\u5173\u952e\u5b57'),
        ),
        migrations.AddField(
            model_name='jiemoduispider',
            name='key_words',
            field=models.CharField(default='\u597d\u672a\u6765', max_length=16, verbose_name='\u5173\u952e\u5b57'),
        ),
        migrations.AddField(
            model_name='kaoyanbangspider',
            name='key_words',
            field=models.CharField(default='\u597d\u672a\u6765', max_length=16, verbose_name='\u5173\u952e\u5b57'),
        ),
        migrations.AddField(
            model_name='tiebaspider',
            name='key_words',
            field=models.CharField(default='\u597d\u672a\u6765', max_length=16, verbose_name='\u5173\u952e\u5b57'),
        ),
        migrations.AddField(
            model_name='toutiaospider',
            name='key_words',
            field=models.CharField(default='\u597d\u672a\u6765', max_length=16, verbose_name='\u5173\u952e\u5b57'),
        ),
        migrations.AddField(
            model_name='wechatspider',
            name='key_words',
            field=models.CharField(default='\u597d\u672a\u6765', max_length=16, verbose_name='\u5173\u952e\u5b57'),
        ),
    ]
