# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-20 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider_board', '0006_auto_20170728_1120'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeneralNewsSpider',
        ),
        migrations.DeleteModel(
            name='JiazhangbangSpider',
        ),
        migrations.DeleteModel(
            name='JiemoduiSpider',
        ),
        migrations.DeleteModel(
            name='KaoyanbangSpider',
        ),
        migrations.DeleteModel(
            name='TiebaSpider',
        ),
        migrations.DeleteModel(
            name='ToutiaoSpider',
        ),
        migrations.DeleteModel(
            name='ZhihuSpider',
        ),
        migrations.AlterField(
            model_name='wechatspider',
            name='db_host',
            field=models.CharField(default='127.0.0.1', max_length=16, verbose_name='Host'),
        ),
        migrations.AlterField(
            model_name='wechatspider',
            name='db_name',
            field=models.CharField(default='xes_app_feed', max_length=32, verbose_name='\u6570\u636e\u5e93\u540d'),
        ),
        migrations.AlterField(
            model_name='wechatspider',
            name='db_password',
            field=models.CharField(default='123456', max_length=32, verbose_name='\u5bc6\u7801'),
        ),
        migrations.AlterField(
            model_name='wechatspider',
            name='db_user',
            field=models.CharField(default='root', max_length=32, verbose_name='\u7528\u6237\u540d'),
        ),
    ]
