# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-26 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider_board', '0008_wechatmasterspider'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovMasterSpider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(default='mov_pub', max_length=20, verbose_name='\u4f7f\u7528\u7684\u722c\u866b\u63a5\u53e3')),
                ('days_range', models.IntegerField(verbose_name='\u65f6\u95f4\u8303\u56f4')),
                ('key_words', models.CharField(default='\u590f\u8001\u5e08\u4f5c\u4e1a', max_length=16, verbose_name='\u5173\u952e\u5b57')),
                ('current_status', models.CharField(default='\u5c31\u7eea', max_length=4, verbose_name='\u5f53\u524d\u72b6\u6001')),
                ('description', models.TextField(blank=True, null=True, verbose_name='\u63cf\u8ff0')),
                ('db_host', models.CharField(default='127.0.0.1', max_length=16, verbose_name='Host')),
                ('db_name', models.CharField(default='xm', max_length=32, verbose_name='\u6570\u636e\u5e93\u540d')),
                ('db_user', models.CharField(default='root', max_length=32, verbose_name='\u7528\u6237\u540d')),
                ('db_password', models.CharField(default='123456', max_length=32, verbose_name='\u5bc6\u7801')),
            ],
            options={
                'verbose_name': '\u5f71\u8bc4\u722c\u53d6-Master',
                'verbose_name_plural': '\u5f71\u8bc4\u722c\u53d6-Master',
            },
        ),
        migrations.CreateModel(
            name='MovSpider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(default='mov_pub', max_length=20, verbose_name='\u4f7f\u7528\u7684\u722c\u866b\u63a5\u53e3')),
                ('days_range', models.IntegerField(verbose_name='\u65f6\u95f4\u8303\u56f4')),
                ('key_words', models.CharField(default='\u590f\u8001\u5e08\u4f5c\u4e1a', max_length=16, verbose_name='\u5173\u952e\u5b57')),
                ('current_status', models.CharField(default='\u5c31\u7eea', max_length=4, verbose_name='\u5f53\u524d\u72b6\u6001')),
                ('description', models.TextField(blank=True, null=True, verbose_name='\u63cf\u8ff0')),
                ('db_host', models.CharField(default='127.0.0.1', max_length=16, verbose_name='Host')),
                ('db_name', models.CharField(default='xm', max_length=32, verbose_name='\u6570\u636e\u5e93\u540d')),
                ('db_user', models.CharField(default='root', max_length=32, verbose_name='\u7528\u6237\u540d')),
                ('db_password', models.CharField(default='123456', max_length=32, verbose_name='\u5bc6\u7801')),
            ],
            options={
                'verbose_name': '\u5f71\u8bc4\u722c\u53d6',
                'verbose_name_plural': '\u5f71\u8bc4\u722c\u53d6',
            },
        ),
        migrations.DeleteModel(
            name='WechatMasterSpider',
        ),
        migrations.DeleteModel(
            name='WechatSpider',
        ),
    ]
