# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-26 15:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spider_board', '0009_auto_20171226_2321'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='movmasterspider',
            table='mov_master_spider',
        ),
        migrations.AlterModelTable(
            name='movspider',
            table='mov_spider',
        ),
    ]
