# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-28 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider_board', '0010_auto_20171226_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movmasterspider',
            name='db_host',
            field=models.CharField(default='45.77.150.109', max_length=16, verbose_name='Host'),
        ),
        migrations.AlterField(
            model_name='movmasterspider',
            name='db_password',
            field=models.CharField(default='d(8Vr!zmmaYrbW?y', max_length=32, verbose_name='\u5bc6\u7801'),
        ),
        migrations.AlterField(
            model_name='movspider',
            name='db_host',
            field=models.CharField(default='45.77.150.109', max_length=16, verbose_name='Host'),
        ),
        migrations.AlterField(
            model_name='movspider',
            name='db_password',
            field=models.CharField(default='d(8Vr!zmmaYrbW?y', max_length=32, verbose_name='\u5bc6\u7801'),
        ),
    ]
