# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-30 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider_board', '0011_auto_20171228_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movmasterspider',
            name='db_password',
            field=models.CharField(default='****************', max_length=32, verbose_name='\u5bc6\u7801'),
        ),
        migrations.AlterField(
            model_name='movmasterspider',
            name='db_user',
            field=models.CharField(default='Ubuntu', max_length=32, verbose_name='\u7528\u6237\u540d'),
        ),
        migrations.AlterField(
            model_name='movspider',
            name='db_password',
            field=models.CharField(default='****************', max_length=32, verbose_name='\u5bc6\u7801'),
        ),
        migrations.AlterField(
            model_name='movspider',
            name='db_user',
            field=models.CharField(default='Ubuntu', max_length=32, verbose_name='\u7528\u6237\u540d'),
        ),
    ]
